CREATE DATABASE IF NOT EXISTS gym_reservation CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE gym_reservation;

-- ============== 权限相关表 ==============
-- 1. 角色表
CREATE TABLE IF NOT EXISTS role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '角色ID',
  role_code VARCHAR(50) NOT NULL UNIQUE COMMENT '角色代码',
  role_name VARCHAR(100) NOT NULL COMMENT '角色名称',
  description VARCHAR(500) COMMENT '描述',
  is_system BOOLEAN NOT NULL DEFAULT false COMMENT '是否系统角色',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

-- 2. 权限表
CREATE TABLE IF NOT EXISTS permission (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '权限ID',
  perm_code VARCHAR(100) NOT NULL UNIQUE COMMENT '权限代码',
  perm_name VARCHAR(100) NOT NULL COMMENT '权限名称',
  perm_type VARCHAR(50) NOT NULL COMMENT '权限类型: MENU, BUTTON, API, DATA',
  parent_id BIGINT DEFAULT 0 COMMENT '父权限ID',
  path VARCHAR(500) COMMENT '路由路径/接口路径',
  component VARCHAR(500) COMMENT '前端组件',
  icon VARCHAR(100) COMMENT '图标',
  sort_order INT DEFAULT 0 COMMENT '排序',
  description VARCHAR(500) COMMENT '描述',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';

-- 3. 默认角色权限配置表（定义角色初始权限）
CREATE TABLE IF NOT EXISTS default_role_permission (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '配置ID',
  role_code VARCHAR(50) NOT NULL COMMENT '角色代码',
  permission_id BIGINT NOT NULL COMMENT '权限ID',
  is_required BOOLEAN NOT NULL DEFAULT true COMMENT '是否必选权限',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_role_permission_default (role_code, permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='默认角色权限配置表';

-- 4. 角色权限关联表（实际用户的权限）
CREATE TABLE IF NOT EXISTS role_permission (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '关联ID',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  permission_id BIGINT NOT NULL COMMENT '权限ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY uk_role_permission (role_id, permission_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关联表';

-- ============== 用户相关表 ==============
-- 5. 用户表（一个用户一个角色）
CREATE TABLE IF NOT EXISTS gym_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
  role_id BIGINT NOT NULL COMMENT '角色ID（一个用户一个角色）',
  phone VARCHAR(20) COMMENT '手机号',
  email VARCHAR(100) COMMENT '邮箱',
  wechat_openid VARCHAR(32) COMMENT '微信OpenID',
  avatar_url VARCHAR(500) COMMENT '头像',
  real_name VARCHAR(50) COMMENT '真实姓名',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE, DISABLED',
  last_login_at DATETIME COMMENT '最后登录时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 6. 用户管理的场馆关联表（场馆管理员可以管理哪些场馆）
CREATE TABLE IF NOT EXISTS user_venue (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '关联ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  venue_id BIGINT NOT NULL COMMENT '场馆ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY uk_user_venue (user_id, venue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户场馆关联表';

-- ============== 场馆场地相关表 ==============
-- 7. 场馆表
CREATE TABLE IF NOT EXISTS venue (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '场馆ID',
  name VARCHAR(128) NOT NULL COMMENT '场馆名称',
  address VARCHAR(255) NOT NULL COMMENT '地址',
  contact_phone VARCHAR(20) COMMENT '联系电话',
  description TEXT COMMENT '描述',
  open_time TIME NOT NULL DEFAULT '08:00:00' COMMENT '开放时间',
  close_time TIME NOT NULL DEFAULT '22:00:00' COMMENT '关闭时间',
  images TEXT COMMENT '图片URL列表(JSON)',
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT '状态: OPEN, CLOSED, MAINTENANCE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='场馆表';

-- 8. 场地表
CREATE TABLE IF NOT EXISTS court (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '场地ID',
  venue_id BIGINT NOT NULL COMMENT '场馆ID',
  name VARCHAR(128) NOT NULL COMMENT '场地名称',
  sport_type VARCHAR(50) NOT NULL COMMENT '运动类型: BASKETBALL, BADMINTON, TENNIS, FITNESS, YOGA, SWIMMING',
  description TEXT COMMENT '描述',
  capacity INT NOT NULL DEFAULT 1 COMMENT '容量',
  images TEXT COMMENT '图片URL列表(JSON)',
  status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' COMMENT '状态: AVAILABLE, MAINTENANCE, CLOSED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='场地表';

-- ============== 预约相关表 ==============
-- 9. 时间段表（每天生成）
CREATE TABLE IF NOT EXISTS timeslot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '时间段ID',
  court_id BIGINT NOT NULL COMMENT '场地ID',
  slot_date DATE NOT NULL COMMENT '日期',
  start_time TIME NOT NULL COMMENT '开始时间',
  end_time TIME NOT NULL COMMENT '结束时间',
  price DECIMAL(10,2) NOT NULL COMMENT '价格',
  status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' COMMENT '状态: AVAILABLE, BOOKED, UNAVAILABLE',
  quota INT NOT NULL DEFAULT 1 COMMENT '可预约数',
  booked_count INT NOT NULL DEFAULT 0 COMMENT '已预约数',
  is_peak BOOLEAN NOT NULL DEFAULT false COMMENT '是否高峰时段',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_court_slot (court_id, slot_date, start_time, end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='时间段表';

-- 10. 预约表
CREATE TABLE IF NOT EXISTS reservation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '预约ID',
  reservation_no VARCHAR(64) NOT NULL UNIQUE COMMENT '预约编号',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  court_id BIGINT NOT NULL COMMENT '场地ID',
  slot_date DATE NOT NULL COMMENT '预约日期',
  start_time TIME NOT NULL COMMENT '开始时间',
  end_time TIME NOT NULL COMMENT '结束时间',
  amount DECIMAL(10,2) NOT NULL COMMENT '金额',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT' COMMENT '状态: PENDING_PAYMENT, PAID, CONFIRMED, IN_PROGRESS, COMPLETED, CANCELLED, REFUNDED',
  participants INT NOT NULL DEFAULT 1 COMMENT '参与人数',
  contact_name VARCHAR(50) COMMENT '联系人',
  contact_phone VARCHAR(20) COMMENT '联系电话',
  cancel_reason VARCHAR(255) COMMENT '取消原因',
  cancelled_at DATETIME COMMENT '取消时间',
  completed_at DATETIME COMMENT '完成时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约表';

-- ============== 支付相关表 ==============
-- 11. 支付表
CREATE TABLE IF NOT EXISTS payment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '支付ID',
  reservation_id BIGINT NOT NULL COMMENT '预约ID',
  payment_no VARCHAR(64) NOT NULL UNIQUE COMMENT '支付单号',
  amount DECIMAL(10,2) NOT NULL COMMENT '支付金额',
  payment_method VARCHAR(20) NOT NULL COMMENT '支付方式: WECHAT, ALIPAY, CASH, BALANCE',
  payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING, SUCCESS, FAILED, REFUNDED',
  transaction_no VARCHAR(64) COMMENT '第三方交易号',
  paid_at DATETIME COMMENT '支付时间',
  refund_amount DECIMAL(10,2) COMMENT '退款金额',
  refunded_at DATETIME COMMENT '退款时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付表';

-- ============== 优惠券相关表 ==============
-- 12. 优惠券表
CREATE TABLE IF NOT EXISTS coupon (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '优惠券ID',
  code VARCHAR(32) NOT NULL UNIQUE COMMENT '优惠券码',
  name VARCHAR(100) NOT NULL COMMENT '名称',
  type VARCHAR(20) NOT NULL COMMENT '类型: AMOUNT, PERCENTAGE',
  value DECIMAL(10,2) NOT NULL COMMENT '面值/折扣',
  min_amount DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '最低消费',
  start_time DATETIME NOT NULL COMMENT '生效时间',
  end_time DATETIME NOT NULL COMMENT '失效时间',
  total_quantity INT NOT NULL COMMENT '总数量',
  used_quantity INT NOT NULL DEFAULT 0 COMMENT '已使用数量',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态: ACTIVE, INACTIVE, EXPIRED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠券表';

-- 13. 用户优惠券表
CREATE TABLE IF NOT EXISTS user_coupon (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  coupon_id BIGINT NOT NULL COMMENT '优惠券ID',
  status VARCHAR(20) NOT NULL DEFAULT 'UNUSED' COMMENT '状态: UNUSED, USED, EXPIRED',
  used_at DATETIME COMMENT '使用时间',
  expire_at DATETIME NOT NULL COMMENT '过期时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '领取时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_user_coupon (user_id, coupon_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户优惠券表';

-- 14. 预约优惠券关联表
CREATE TABLE IF NOT EXISTS reservation_coupon (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID',
  reservation_id BIGINT NOT NULL COMMENT '预约ID',
  user_coupon_id BIGINT NOT NULL COMMENT '用户优惠券ID',
  discount_amount DECIMAL(10,2) NOT NULL COMMENT '优惠金额',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约优惠券关联表';

-- ============== 其他功能表 ==============
-- 15. 公告表
CREATE TABLE IF NOT EXISTS announcement (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '公告ID',
  title VARCHAR(200) NOT NULL COMMENT '标题',
  content TEXT NOT NULL COMMENT '内容',
  type VARCHAR(20) NOT NULL DEFAULT 'SYSTEM' COMMENT '类型: SYSTEM, ACTIVITY, VENUE',
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT, PUBLISHED, EXPIRED',
  publish_time DATETIME COMMENT '发布时间',
  expire_time DATETIME COMMENT '过期时间',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告表';

-- 16. 反馈表
CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '反馈ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  type VARCHAR(20) NOT NULL COMMENT '类型: COMPLAINT, SUGGESTION, QUESTION',
  title VARCHAR(200) COMMENT '标题',
  content TEXT NOT NULL COMMENT '内容',
  rating INT COMMENT '评分(1-5)',
  reply TEXT COMMENT '回复',
  replied_at DATETIME COMMENT '回复时间',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING, PROCESSING, RESOLVED, CLOSED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='反馈表';

-- 17. 收藏表
CREATE TABLE IF NOT EXISTS favorite (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '收藏ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  target_type VARCHAR(20) NOT NULL COMMENT '类型: COURT, VENUE',
  target_id BIGINT NOT NULL COMMENT '目标ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY uk_user_favorite (user_id, target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='收藏表';

-- 18. 操作日志表
CREATE TABLE IF NOT EXISTS operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '日志ID',
  user_id BIGINT COMMENT '用户ID',
  action VARCHAR(100) NOT NULL COMMENT '操作',
  module VARCHAR(50) NOT NULL COMMENT '模块',
  target_type VARCHAR(50) COMMENT '目标类型',
  target_id BIGINT COMMENT '目标ID',
  ip VARCHAR(50) COMMENT 'IP地址',
  user_agent VARCHAR(500) COMMENT 'UserAgent',
  details TEXT COMMENT '详情(JSON)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
